#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BabyShop.Resource", IsApplication=true)]

namespace BabyShop
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class IdLogar
		{
			
			// aapt resource value: 0x7f080008
			public const int btnLogar = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int btnNovo = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int lblEmail = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int lblLogin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int lblMensagem = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int lblSenha = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int llApp = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int llControles = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int txtEmail = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int txtSenha = 2131230727;
			
			static IdLogar()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdLogar()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class IdAtualizar
		{
			
			// aapt resource value: 0x7f060019
			public const int btnExcluir = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int btnSalvar = 2131099672;
			
			// aapt resource value: 0x7f060003
			public const int hfDataCadastro = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int hfIdCliente = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int lblCPF = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int lblDadosAcesso = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int lblDadosPessoais = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int lblEmail = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int lblEndereco = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int lblEstado = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int lblMensagem = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int lblMunicipio = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int lblNomeCompleto = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int lblSenha = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int lblTelefone = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int llBotoes = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int llDadosAcesso = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int llDadosPessoais = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int txtCPF = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int txtEmail = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int txtEndereco = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int txtEstado = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int txtMunicipio = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int txtNomeCompleto = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int txtSenha = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int txtTelefone = 2131099670;
			
			static IdAtualizar()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdAtualizar()
			{
			}
		}
		
		public partial class IdCadastrar
		{
			
			// aapt resource value: 0x7f070015
			public const int btnSalvar = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int lblCPF = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int lblDadosAcesso = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int lblDadosPessoais = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int lblEmail = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int lblEndereco = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int lblEstado = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int lblMensagem = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int lblMunicipio = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int lblNomeCompleto = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int lblSenha = 2131165189;
			
			// aapt resource value: 0x7f070013
			public const int lblTelefone = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int llDadosAcesso = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int llDadosPessoais = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int txtCPF = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int txtEmail = 2131165188;
			
			// aapt resource value: 0x7f070012
			public const int txtEndereco = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int txtEstado = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int txtMunicipio = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int txtNomeCompleto = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int txtSenha = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int txtTelefone = 2131165204;
			
			static IdCadastrar()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdCadastrar()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Atualizar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Cadastrar = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Logar = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int MSG00001 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MSG00002 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int MSG00003 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int MSG00004 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int MSG00005 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int MSG00006 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int MSG00007 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
